import turtle

def draw_square(some_turtle):
    for i  in range(1,5):
        some_turtle.forward(100)
        some_turtle.right(90)
def draw_shape(some_turtle):
    some_turtle.circle(50)
def draw_stem(some_turtle):
    some_turtle.right(90)
    some_turtle.penup()
    some_turtle.forward(100)
    some_turtle.pendown()
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(1)
    some_turtle.right(90)
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(3)
    some_turtle.right(90)
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(4)
    some_turtle.right(90)
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(5)
    some_turtle.right(90)
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(6)
    some_turtle.right(90)
    some_turtle.forward(200)
    some_turtle.right(90)
    some_turtle.forward(7)
    some_turtle.right(90)
    some_turtle.forward(200)

def draw_word(some_turtle):
    some_turtle.left(145)
    some_turtle.penup()
    some_turtle.forward(375)
    some_turtle.pendown()
    some_turtle.pencolor("red")
    some_turtle.write("A Rose by Any Other Name", font=("Segoe Script", 30, "normal"))
    some_turtle.left(125)
    some_turtle.penup()
    some_turtle.forward(50)
    some_turtle.pendown()
    some_turtle.pencolor("gold")
    some_turtle.write("Would Smell as Sweet", font=("Segoe Script", 20, "normal"))
    some_turtle.penup()
    some_turtle.forward(375)
    some_turtle.pendown()
    some_turtle.pencolor("blue")
    some_turtle.write("Steven D. Morrison", font=("Segoe Script", 17, "normal"))
    some_turtle.left(90)
    some_turtle.penup()
    some_turtle.forward(400)
    some_turtle.pendown()
    some_turtle.pencolor("purple")
    some_turtle.write("June 2 2015", font=("Segoe Script", 17, "normal"))
    
    
def draw_art():
    window = turtle.Screen()
    window.bgcolor("black")
    izzy = turtle.Turtle()
    izzy.shape("blank")
    izzy.color("purple")
    izzy.speed(0)
    sam = turtle.Turtle()
    sam.shape("blank")
    sam.color("orange")
    sam.speed(0)
    steve = turtle.Turtle()
    steve.shape("blank")
    steve.color("green")
    steve.speed(0)
    draw_stem(steve)
    for i  in range(1,20):
        draw_square(izzy)
        izzy.right(10)
        draw_square(sam)
        sam.left(10)
    angie = turtle.Turtle()
    angie.shape("circle")
    angie.color("red","gold")
    angie.speed(0)
    chan = turtle.Turtle()
    chan.shape("blank")
    chan.color("Blue")
    chan.speed(0)
    for i  in range(1,20):
        draw_shape(angie)
        angie.right(15)
        draw_shape(chan)
        chan.left(15)
    cute = turtle.Turtle()
    cute.color("red")
    cute.shape("blank")
    draw_word(cute)
        
    window.exitonclick()

draw_art()
